name: Test & Build
on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: env
      url: https://github.com
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - name: Test
      run: make test
    - name: Embed Keys
      env:
        key: ${{ secrets.API_KEY }}
        secret: ${{ secrets.API_SECRET }}
      run: make embed-keys
    - name: Build
      run: make cross-compile